CREATE TABLE Vote (
    voteid INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1,
    INCREMENT BY 1),
    pollid INTEGER NOT NULL,
    username VARCHAR(50) NOT NULL,
    choice VARCHAR(50) NOT NULL,
    PRIMARY KEY (voteid),
    FOREIGN KEY (pollid) REFERENCES POLL(pollid)
);